networks:
  fantasy_net:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  # 1. Appsmith Service (Includes its own MongoDB and Redis)
  appsmith:
    image: index.docker.io/appsmith/appsmith-ee
    container_name: appsmith
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./appsmith_stacks:/appsmith-stacks # Volume for persistent Appsmith data
    environment:
      APPSMITH_CUSTOM_DOMAIN: http://localhost
    networks:
      - fantasy_net
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "rust_api:172.28.0.10"

  # 2. Your Custom Rust API Service
  rust_api:
    build: .
    container_name: mfl_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      fantasy_net:
        ipv4_address: 172.28.0.10